pipeline {
    agent {
      docker { image 'node:16-alpine' }
    }

    stages {
        stage('Testing node version') {
            steps {
                sh 'node --version'
            }
        }
    }
}
